# Generated by Django 3.0.7 on 2020-07-19 03:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_moviereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHashTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='moviereview',
            name='movie_backdroppath',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='movie_posterpath',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review_public_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review_slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='movie_review',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review_hash',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ReviewHashTag'),
        ),
    ]
