# Generated by Django 3.0.7 on 2020-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200719_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ReviewHashTag',
        ),
    ]
