# Generated by Django 3.0.7 on 2020-06-21 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmeta',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=30)),
                ('screen_location', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=10)),
                ('show_date', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_poster', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('seats_count', models.IntegerField()),
                ('seats', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('secret_key', models.CharField(max_length=10)),
                ('booking_meta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.Bookingmeta')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
