# Generated by Django 3.0.7 on 2020-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=30)),
                ('screen_location', models.CharField(max_length=60)),
                ('screen_shows', models.CharField(choices=[('Morning', '09.00 AM'), ('Noon', '12.00 PM'), ('Matinee', '03.00 PM'), ('Evening', '06.00 PM'), ('Night', '10.00 PM')], max_length=10)),
            ],
        ),
    ]
