# Generated by Django 3.0.7 on 2020-06-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screens',
            new_name='Screen',
        ),
    ]
