# Generated by Django 3.0.7 on 2020-06-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200616_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='screen_shows',
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_location',
            field=models.CharField(max_length=30),
        ),
    ]
