# Generated by Django 3.0.7 on 2020-06-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20200616_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('secret_key', models.CharField(max_length=10)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=30)),
                ('screen_location', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('seats', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
