# Generated by Django 3.0.7 on 2020-06-18 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200616_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmeta',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=30)),
                ('screen_location', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=10)),
                ('show_date', models.CharField(max_length=10)),
                ('movie_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('seats_count', models.IntegerField()),
                ('seats', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='screen_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='screen_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_meta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.Bookingmeta'),
        ),
    ]
